<a href="https://colab.research.google.com/github/raganu89/Pytorch/blob/main/1_tensors_in_pytorch.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [2]:
import torch
print(torch.__version__)

2.6.0+cu124


In [5]:
if torch.cuda.is_available():
    print("CUDA is available")
    print(torch.cuda.get_device_name())
else:
    print("CUDA is not available")

CUDA is available
Tesla T4


In [7]:
#creating empty tensor
a = torch.empty(2,3)
type(a)

torch.Tensor

In [11]:
#zeros
b = torch.zeros(2,3)
print(b)
type(b)

tensor([[0., 0., 0.],
        [0., 0., 0.]])


torch.Tensor

In [10]:
#ones
c = torch.ones(2,3)
print(c)
type(c)

tensor([[1., 1., 1.],
        [1., 1., 1.]])


torch.Tensor

In [12]:
#rand
d = torch.rand(2,3)
print(d)
type(d)

tensor([[0.9640, 0.1823, 0.2847],
        [0.7712, 0.9850, 0.4712]])


torch.Tensor

In [13]:
#manual seed sothat random values remain same
torch.manual_seed(42)
e = torch.rand(2,3)
print(e)
type(e)

tensor([[0.8823, 0.9150, 0.3829],
        [0.9593, 0.3904, 0.6009]])


torch.Tensor

In [15]:
#using tensorcreate tensor
torch.tensor([[1,2,3],[4,5,6]])

tensor([[1, 2, 3],
        [4, 5, 6]])

In [16]:
device = torch.device("cuda" if torch.cuda.is_available() else "cpu")
torch.rand((2,3),device=device)

tensor([[0.6130, 0.0101, 0.3984],
        [0.0403, 0.1563, 0.4825]], device='cuda:0')